version: '4.3'
services:
  spotify-postgresql:
    image: postgres:15
    container_name: spotify-postgres
    environment:
      - POSTGRES_USER=julien
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data