logging:
  level:
    ROOT: info
    '[org.hibernate.SQL]': DEBUG
    '[fr.julien.spotify_clone_back]': DEBUG

spring:
  profiles:
    active: dev
  application:
    name: spotify
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${postgres_url}:5432/${postgres_db}
    username: ${postgres_username}
    password: ${postgres_password}
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[default_schema]': spotify
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: spotify
    enabled: true
    #    drop-first: true
  servlet:
    multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB
server:
    port: 8080

okta:
    oauth2:
      issuer: ${AUTH0_ISSUER}
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}