logging:
  level:
    ROOT: info
    org.hibernate.SQL: DEBUG
    fr.codecake.spotifyclone: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: spotify
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/spotify
    username: julien
    password: 
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: spotify
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: spotify
    enabled: true
    #    drop-first: true
  servlet:
    multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB
server:
    port: 8080

# okta:
#     oauth2:
#     issuer: https://spotify-clone.jp.auth0.com/
#     client-id: ${auth0_client_id}
#     client-secret: ${auth0_client_secret}